New york time index page
rukundoeric/Positioning-and-Floating-Elements pull request #1
Opened 2020-09-25 11:19 UTC by rukundoeric

### What does this do? 
*  Floating and positioning elements
### Description of Task to be completed? 
* A structural clone of the New York Times page.
### How should this be manually tested? 
* Clone this repo https://github.com/rukundoeric/Positioning-and-Floating-Elements/tree/nyt-index-page
* Navigate to project directory.
* If you have a live server in you vs-code, just run it.
* Otherwise just open the index page with your browser.

2020-09-25 11:48 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-25 12:01 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @rukundoeric AND @Lameck1 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes  👇.
- [ ] Use a single image in  **The Theory of Inflation** section([Image](https://static01.nyt.com/newsgraphics/2014/03/18/theory-of-inflation/1ebaa1b972edda0f407fbaa0e010f6b50fb6792e/inflation-945.png))
- [ ] Use image  URL in image src attribute in **Editors' Picks**
Example: 
`<img alt="" src="https://static01.nyt.com/images/2020/09/27/fashion/27MODERN-AGEGAP/27MODERN-AGEGAP-threeByTwoSmallAt2X.jpg?quality=75&amp;auto=webp&amp;disable=upscale" decoding="async" itemprop="url" itemid="https://static01.nyt.com/images/2020/09/27/fashion/27MODERN-AGEGAP/27MODERN-AGEGAP-threeByTwoSmallAt2X.jpg?quality=75&amp;auto=webp&amp;disable=upscale">`
- [x] Remove comments and `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)

- [x] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/94264086-82317500-ff4f-11ea-88fd-a60f78d70421.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/)




##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    /* stylelint-disable */
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    /* stylelint-disable */
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    /* stylelint-disable */
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +      /* stylelint-disable */
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +        /* stylelint-disable */
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +          /* stylelint-disable */
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +      /* stylelint-enable */ }
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +      /* stylelint-enable */ }
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    /* stylelint-disable */
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    /* stylelint-enable */ }
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    /* stylelint-enable */ }
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +      /* stylelint-enable */ }
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +      /* stylelint-enable */ }
Remove comments

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +  padding: 0 10px !important;
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +      font-weight: 200 !important;
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    position: relative !important; }
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    color: #326891 !important; }
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +      margin: 0 !important; }
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +          color: #6b6666 !important;
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +    width: 50% !important; }
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +        border-left: 1px solid #c5c5c5 !important; }
Remove `!important`

2020-09-25 12:01 UTC, umairarshadbutt commented on css/style.css
> +          border-bottom: 1px solid #c5c5c5 !important; }
Remove `!important`

2020-09-25 16:47 UTC, javitocor requested changes
#STATUS CHANGES REQUIRED ♻️ 

Great job with the changes 👍 
However, still some more changes to do before approving the project
Check my comments below 👇  and resubmit the project for a new code review ⏩ 

Good luck, team 😃 

- The NY times logo on the header must be a link, please fix it    
   - The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

- Kindly modify the theory of inflation section, now the text overlap the images
![Capture](https://user-images.githubusercontent.com/56809963/94293774-19ea8f80-ff5f-11ea-8b57-4ec45ca7dd10.PNG)

- Kindly, modify the most popular section, must be similar to the original, now it is only half of its width
![Capture2](https://user-images.githubusercontent.com/56809963/94293855-3ab2e500-ff5f-11ea-97e5-8e99441f0297.PNG)
![Capture1](https://user-images.githubusercontent.com/56809963/94293857-3be41200-ff5f-11ea-87e0-bd413adb8f69.PNG)

[OPTIONAL]
- Add cursor pointer to the social media icons and header buttons
- You can use `section` tag and not repeat `div` that often, it is a good practice to use semantic HTML tags

2020-09-27 17:35 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hello, @rukundoeric  and @Lameck1 👋   

You've done an awesome job so far 👌. I see you have fixed the *The theory of inflation* section, well done. Just make these few changes and you will be good to go.

### Please only submit for Code Review Request when you are ready, I noticed you were making some changes while I was reviewing your codes

- [ ] We have to make sure your page design isn't messed up. Reduce the font-size of the footer to match the original 
![footer](https://user-images.githubusercontent.com/5264771/94371596-94e2b000-00ef-11eb-9be1-bee2acdd6d4f.jpg)

- [ ] Fix the missing image on the first article of *More in Space and Astronomy* section. 
<img width="528" alt="Screen Shot 2020-09-27 at 6 32 00 PM" src="https://user-images.githubusercontent.com/5264771/94371645-e854fe00-00ef-11eb-999b-f30446452246.png">


### Add these changes and submit another code review request.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-09-27 20:28 UTC, teekaytech requested changes
## Status: Changes Required :warning:

### Hi team :wave:

**A lot of efforts have been put into this project. You've really done well to implement the changes required by previous reviewers. However, we still have to put one-to-two things in place before this project can be approved.**

- Let us improve on the `Editor's Pick` section. Looking at our clone (observe from the image below), the layout looks a bit different from the source.
Source (original):
![21:10:50](https://user-images.githubusercontent.com/26856491/94374921-a0da6c00-0107-11eb-9cb4-900e2a45a91f.png)

Clone (ours):
![21:14:34](https://user-images.githubusercontent.com/26856491/94374929-ae8ff180-0107-11eb-975b-94ea516524bb.png)

**[ OPTIONAL ]**
- Still talking about looks, let's reduce the font size of the footer so it can be close to the source size.

Source (original):
![21:11:55](https://user-images.githubusercontent.com/26856491/94374945-daab7280-0107-11eb-8f40-078097f6a88e.png) 

Clone (ours):
![21:15:47](https://user-images.githubusercontent.com/26856491/94374950-e303ad80-0107-11eb-9c99-fce8239b6639.png)

**We're almost there: do not panic. Kindly make the changes above and request for another review when you are done.**

**You can reach me @taofeekolalere on slack.
Happy Coding :man_technologist:**

2020-09-28 04:59 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:

Hello Developer,

I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-09-28 05:20 UTC, merged